#!/bin/bash

star="\e[5;33m*\e[0m\e[1;32m"
o="\e[1m\e[1;31mo\e[0m\e[1;32m"
merry="Feliz"
xmas="Natal"
reset="\033[0m"

clear
echo "bash-5.1$"
echo -e "
    ${star}
   /.\\ \t\t${merry}
  /${o}..\\ \t${xmas}
  /..${o}\\
 /.${o}..${o}\\	
 /...${o}.\\
/..${o}....\\
^^^[_]^^^
${reset}
"
